---
project:
  type: book

book:
  title: "CanadaLogin Metrics Cookbook"
  author: "Colin Douglas"
  date: today
  chapters:
    - index.qmd
    - part: "Metrics Cookbook"
      chapters:
        - 01-ibm-verify.qmd
        - 02-call-centre.qmd
#        - 03-cross-source.qmd
#        - 90-notes.qmd
    - part: "Data Catalog"
      chapters:
        - catalog/index.qmd
        - catalog/ibm_verify.qmd
        - catalog/call_centre.qmd

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    number-sections: false
    theme: cosmo

execute:
  echo: true
  warning: false
  message: false
